M48
; DRILL file {KiCad 9.0.6} date 2026-05-30T01:47:26+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-30T01:47:26+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.150
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
%
G90
G05
T1
X228.125Y-83.962
T2
X249.125Y-83.962
T3
X176.0Y-66.25
X176.0Y-85.0
X210.5Y-67.5
M30
