M48
; DRILL file {KiCad 9.0.6} date 2026-05-31T00:00:56+0530
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-05-31T00:00:56+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0453
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0984
%
G90
G05
T1
X8.9813Y-3.3056
T2
X9.8081Y-3.3056
T3
X6.9291Y-2.6083
X6.9291Y-3.3465
X8.2874Y-2.6575
M30
